version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean install -DskipTests
      - echo Logging in to Amazon ECR...
      - echo AWS_ACCOUNT_ID
      - echo $AWS_ACCOUNT_ID
      - echo DEFAULT_REGION
      - echo $AWS_DEFAULT_REGION
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 260624988989.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=260624988989.dkr.ecr.us-$AWS_DEFAULT_REGION.amazonaws.com/springboot
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t springboot .
      - echo Tagging Docker image...
      - docker tag springboot:latest 260624988989.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/springboot:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 260624988989.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/springboot:latest
